---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: atomic-yellow-dell
description: Atomic Yellow for Dell laptops with Broadcom fingerprint support and Intel media driver.

base-image: ghcr.io/buggerman/atomic-yellow
image-version: latest

modules:
  - type: files
    files:
      - source: system
        destination: /

  - type: dnf
    repos:
      copr:
        - grahamwhiteuk/libfprint-tod

  - type: script
    scripts:
      - broadcom-fingerprint.sh

  - type: dnf
    install:
      packages:
        - libfprint-2-tod1-broadcom
        - libfprint-tod-selinux
        - intel-media-driver

  - type: signing
