---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: atomic-yellow-dell
description: Atomic Yellow for Dell laptops with Broadcom fingerprint, codecs, and power management.

base-image: quay.io/fedora-ostree-desktops/cosmic-atomic
image-version: "43"

modules:
  - type: files
    files:
      - source: system
        destination: /

  - type: dnf
    repos:
      copr:
        - grahamwhiteuk/libfprint-tod
    install:
      packages:
        - libavcodec-freeworld
        - gstreamer1-plugins-bad-freeworld
        - gstreamer1-plugins-ugly
        - gstreamer1-vaapi
        - tlp
        - tlp-rdw

  - type: script
    scripts:
      - broadcom-fingerprint.sh

  - type: dnf
    install:
      packages:
        - libfprint-2-tod1-broadcom
        - libfprint-tod-selinux
        - intel-media-driver
        - smbios-utils

  - type: systemd
    system:
      enabled:
        - thermald.service
        - tlp.service

  - type: signing
